### ISSUE TITLE
Accessing 'prop' of a Column

### ISSUE THREAD

**Issue by mahenzon** [AdCombo/combojsonapi#1]
I've faced an issue when there's a Column in a model and another column uses the same name for a column, passed in the Column object, the PermissionPlugin fails processing it. Here's an example:

```python
from flask import Flask
from flask_rest_jsonapi import Api, ResourceList
from combojsonapi.spec import ApiSpecPlugin
from combojsonapi.permission.permission_plugin import PermissionPlugin
from marshmallow_jsonapi import fields, Schema

from sqlalchemy import Column, Integer, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, scoped_session

from logging import getLogger as get_logger

logger = get_logger()
engine = create_engine("sqlite:///:memory:")
Session = scoped_session(sessionmaker())
Base = declarative_base(bind=engine)


class MyModel(Base):
    __tablename__ = "model"

    id = Column(Integer, primary_key=True)
    # creating a column
    model_type = Column(Integer)
    # for no reason creating a column
    # which takes the same name for no reason
    model_entity = Column("model_type", Integer)


class MyModelSchema(Schema):
    class Meta:
        model = MyModel
        type_ = "model"
        self_view = "model_detail"
        self_view_kwargs = {"id": "<id>"}
        self_view_many = "model_list"

    id = fields.Integer(as_string=True)


class MyModelResourceList(ResourceList):
    schema = MyModelSchema
    methods = ["GET"]
    data_layer = {
        "session": Session,
        "model": MyModel,
    }


def setup_openapi(app: Flask):
    app.config["OPENAPI_URL_PREFIX"] = "/api/swagger"
    app.config["OPENAPI_SWAGGER_UI_PATH"] = "/"
    app.config["OPENAPI_SWAGGER_UI_VERSION"] = "3.22.0"


def main():
    app = Flask(__name__)

    @app.errorhandler(Exception)
    def handle_bad_request(e):
        logger.error("here it is:", exc_info=e)
        return "eroro", 500

    setup_openapi(app)

    api_spec = ApiSpecPlugin(
        app=app,
        tags={"MyModels": "API MyModels"},
    )

    api_json = Api(
        app,
        plugins=(
            api_spec,
            PermissionPlugin(strict=False),
        ),
    )
    api_json.route(MyModelResourceList, "model_list", "/api/model/", tag="MyModels")
    app.run(debug=True)


if __name__ == "__main__":
    main()
```

When trying to access `"/api/model/"` I get the following error:
```
here it is:
Traceback (most recent call last):
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/src/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 717, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute 'prop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 45, in wrapper
    return func(*args, **kwargs)
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 87, in wrapper
    raise e
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 71, in dispatch_request
    response = method(*args, **kwargs)
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 45, in wrapper
    return func(*args, **kwargs)
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/src/combojsonapi/combojsonapi/permission/permission_plugin.py", line 63, in wrapper
    return method(*args, **kwargs, _permission_user=permission_user)
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 118, in get
    objects_count, objects = self.get_collection(qs, kwargs)
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 220, in get_collection
    return self._data_layer.get_collection(qs, kwargs)
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/src/flask-rest-jsonapi/flask_rest_jsonapi/data_layers/alchemy.py", line 150, in get_collection
    self_json_api=self)
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/src/combojsonapi/combojsonapi/permission/permission_plugin.py", line 372, in data_layer_get_collection_update_query
    name_columns = list(set(name_columns) & set(get_columns_for_query(self_json_api.model)))
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/src/combojsonapi/combojsonapi/permission/permission_plugin.py", line 36, in get_columns_for_query
    and isinstance(getattr(value, 'prop'), ColumnProperty):
  File "/home/khorenyan/.local/share/virtualenvs/core-C3GrfXXb/src/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 721, in __getattr__
    % (type(self).__name__, type(self.comparator).__name__, key)
AttributeError: Neither 'Column' object nor 'Comparator' object has an attribute 'prop'
127.0.0.1 - - [10/Apr/2020 01:07:12] "GET /api/model/?page%5Bnumber%5D=1&page%5Bsize%5D=10 HTTP/1.1" 500 -
```

So, the error is `AttributeError: Neither 'Column' object nor 'Comparator' object has an attribute 'prop'`.

I'll create a PR for proper attributes checks :smile:

**Comment by Znbiz** [comment]
1. sqlalchemy issues a warning that such use is incorrect:
```
SAWarning: On class 'MyModel', Column object 'model_type' named directly multiple times, only one will be used: model_entity, model_type. Consider using orm.synonym instead
  % (self.classname, name, (", ".join(sorted(keys))))
```

2. If you apply your decision and if you add an MyModelPermission class 
```python
class MyModelPermission(PermissionMixin):
    FIELDS = ['id', 'model_type']

    def get(self, *args, many=True, user_permission: PermissionUser = None, **kwargs) -> PermissionForGet:
        self.permission_for_get.allow_columns = (self.FIELDS, 0,)
        return self.permission_for_get
```
Result:
```
Traceback (most recent call last):
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 717, in __getattr__
    return getattr(self.comparator, key)
AttributeError: 'Comparator' object has no attribute 'property'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 45, in wrapper
    return func(*args, **kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 87, in wrapper
    raise e
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 71, in dispatch_request
    response = method(*args, **kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 45, in wrapper
    return func(*args, **kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/combojsonapi/combojsonapi/permission/permission_plugin.py", line 65, in wrapper
    return method(*args, **kwargs, _permission_user=permission_user)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 118, in get
    objects_count, objects = self.get_collection(qs, kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 220, in get_collection
    return self._data_layer.get_collection(qs, kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/data_layers/alchemy.py", line 150, in get_collection
    self_json_api=self)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/combojsonapi/combojsonapi/permission/permission_plugin.py", line 380, in data_layer_get_collection_update_query
    query = query.options(load_only(*name_columns))
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/query.py", line 1530, in options
    return self._options(False, *args)
  File "<string>", line 2, in _options
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/query.py", line 1549, in _options
    opt.process_query(self)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/strategy_options.py", line 172, in process_query
    self._process(query, True)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/strategy_options.py", line 632, in _process
    raiseerr,
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/strategy_options.py", line 810, in _bind_loader
    raiseerr,
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/strategy_options.py", line 239, in _generate_path
    attr = found_property = attr.property
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/sql/elements.py", line 721, in __getattr__
    % (type(self).__name__, type(self.comparator).__name__, key)
AttributeError: Neither 'Column' object nor 'Comparator' object has an attribute 'property'
```
the problem will go down one level in sqlalchemy

**Comment by Znbiz** [comment]
The issue raised showed another issue. This function returns the name of the columns directly in the database.
```python
def get_columns_for_query(model) -> List[str]:
    """
    Получаем список название атрибутов в моделе, именно как они названы в моделе, т.е., если у нас вот так описано поле
    _permissions = Column('permissions', JSONB, nullable=False), то в columns будет _permissions.
    :param model: модель sqlalchemy
    :return:
    """
    columns = []
    for key, value in model.__dict__.items():
        # Оставляем только атрибуты Column
        if (isinstance(value, InstrumentedAttribute) or isinstance(value, Column)) \
                and (hasattr(value, 'prop') and isinstance(value.prop, ColumnProperty)):
            columns.append(value.expression.description)
    return columns
```

Then he takes the result and looks at the intersection with a list of columns specified in the MyModelPermission class

For example:
```python
class MyModel(Base):
    __tablename__ = "model"

    id = Column(Integer, primary_key=True)
    # creating a column
    model_type = Column('_model_type', Integer)

class MyModelPermission(PermissionMixin):
    FIELDS = ['id', '_model_type']

    def get(self, *args, many=True, user_permission: PermissionUser = None, **kwargs) -> PermissionForGet:
        self.permission_for_get.allow_columns = (self.FIELDS, 0,)
        return self.permission_for_get
```
We get the following ` ['id', '_model_type']`. And then it goes to: https://github.com/AdCombo/combojsonapi/blob/master/combojsonapi/permission/permission_plugin.py#L378

And here an error occurs:
```
Traceback (most recent call last):
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/strategy_options.py", line 229, in _generate_path
    attr = getattr(ent.class_, attr)
AttributeError: type object 'MyModel' has no attribute '_model_type'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 45, in wrapper
    return func(*args, **kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 87, in wrapper
    raise e
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 71, in dispatch_request
    response = method(*args, **kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 45, in wrapper
    return func(*args, **kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/combojsonapi/combojsonapi/permission/permission_plugin.py", line 66, in wrapper
    return method(*args, **kwargs, _permission_user=permission_user)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 118, in get
    objects_count, objects = self.get_collection(qs, kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 220, in get_collection
    return self._data_layer.get_collection(qs, kwargs)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/flask-rest-jsonapi/flask_rest_jsonapi/data_layers/alchemy.py", line 150, in get_collection
    self_json_api=self)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/combojsonapi/combojsonapi/permission/permission_plugin.py", line 381, in data_layer_get_collection_update_query
    query = query.options(load_only(*name_columns))
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/query.py", line 1530, in options
    return self._options(False, *args)
  File "<string>", line 2, in _options
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/query.py", line 1549, in _options
    opt.process_query(self)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/strategy_options.py", line 172, in process_query
    self._process(query, True)
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/strategy_options.py", line 632, in _process
    raiseerr,
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/strategy_options.py", line 810, in _bind_loader
    raiseerr,
  File "/home/znbiz/.local/share/virtualenvs/core-XDWOM1ZM/src/sqlalchemy/lib/sqlalchemy/orm/strategy_options.py", line 234, in _generate_path
    "%s in this Query." % (attr, ent)
sqlalchemy.exc.ArgumentError: Can't find property named "permissions" on mapped class MyModel->_model_type in this Query.
```

**Comment by Znbiz** [comment]
Rewrite as I suggested
https://github.com/AdCombo/combojsonapi/pull/2#discussion_r409922600
