### ISSUE TITLE
AttributeError: 'ParsedRequirement' object has no attribute 'req'" during install in pip>=20.1

### ISSUE THREAD

**Issue by onyxim** [AdCombo/combojsonapi#15]
During install on pip>=20.1 get error message like this:
```bash
Command errored out with exit status 1:', '     command: /home/sergey/.local/share/virtualenvs/core-tv-49RKY/bin/python3.6m -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/home/sergey/.local/share/virtualenvs/core-tv-49RKY/src/combojsonapi/setup.py\'"\'"\'; __file__=\'"\'"\'/home/sergey/.local/share/virtualenvs/core-tv-49RKY/src/combojsonapi/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' egg_info --egg-base /tmp/pip-pip-egg-info-h_qkc943', '         cwd: /home/sergey/.local/share/virtualenvs/core-tv-49RKY/src/combojsonapi/', '    Complete output (9 lines):', '    Traceback (most recent call last):', '      File "<string>", line 1, in <module>', '      File "/home/sergey/.local/share/virtualenvs/core-tv-49RKY/src/combojsonapi/setup.py", line 54, in <module>', '        install_requires=get_requirements(),', '      File "/home/sergey/.local/share/virtualenvs/core-tv-49RKY/src/combojsonapi/setup.py", line 31, in get_requirements', '        return [str(ir.req) for ir in install_reqs]', '      File "/home/sergey/.local/share/virtualenvs/core-tv-49RKY/src/combojsonapi/setup.py", line 31, in <listcomp>', '        return [str(ir.req) for ir in install_reqs]', "    AttributeError: 'ParsedRequirement' object has no attribute 'req'", '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by onyxim** [comment]
Fixed in https://github.com/AdCombo/combojsonapi/commit/d3814c88652eafdd6345820fb2b736998c46c1d7

**Comment by onyxim** [comment]
Linked with AC-5692
